/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Pegawai;
import entity.Tunjangan;
import entity.viewTunjangan;
import implement.PegawaiImplement;
import implement.TunjanganImplement;
import java.sql.SQLException;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import utility.DateUtility;

/**
 *
 * @author aa
 */
public class FormDaftarTunjangan extends javax.swing.JInternalFrame {
List<viewTunjangan> record=new ArrayList<>();
DateUtility du = new DateUtility();
TunjanganImplement vTService;

int row;
    /**
     * Creates new form FormDaftarTunjangan
     */
    public FormDaftarTunjangan() {
        initComponents();
        vTService=new TunjanganImplement();
         
            tabelDaftarTunjangan.getSelectionModel().addListSelectionListener((ListSelectionEvent e)->{
            row = tabelDaftarTunjangan.getSelectedRow();
            if(row!=-1){
            isiText();
            }
        });
         statusAwal();
    }
    
    void statusAwal(){
        //kosongkanText();
        loadData();
        isiTabel();
    }
    void isiTabel(){
         tabelDaftarTunjangan.clearSelection();
        Object data[][] = new Object[record.size()][13];
        int x = 0;
        for(viewTunjangan t:record){
            data[x][0] = t.getIdTunjangan();
            data[x][1] = t.getidPegawai();
            data[x][2] = t.getNamaPegawai();
            data[x][3] = t.getTanggal();
            data[x][4] = t.getPeriodeBulan();
            data[x][5] = t.getPeriodeTahun();
            data[x][6] = t.getNamaTunjangan();
            data[x][7] = t.getNilaiTunjangan();
            x++;
        }
            String judul[] = {"ID Tunjangan","ID_Pegawai","Nama Pegawai","Tanggal","Bulan","Tahun","Tunjangan","Nilai"};
        tabelDaftarTunjangan.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tabelDaftarTunjangan);
      setWidth();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarTunjangan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmdRubah = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        txtIdTunjangan = new javax.swing.JTextField();

        tabelDaftarTunjangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelDaftarTunjangan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Tunjangan");

        cmdRubah.setText("Rubah");
        cmdRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRubahActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cmdRubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdHapus)
                        .addGap(262, 262, 262)
                        .addComponent(txtIdTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addComponent(cmdKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdRubah)
                    .addComponent(cmdKeluar)
                    .addComponent(cmdHapus)
                    .addComponent(txtIdTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
       String cekId = txtIdTunjangan.getText();
        int po=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin menghapus data","Hapus Data",JOptionPane.YES_NO_OPTION);
        if(po==0){
        if(cekId.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
        }else{
            try{
                Pegawai p = new Pegawai();
                String id = txtIdTunjangan.getText();
                vTService.delete(id);
          
                        JOptionPane.showMessageDialog(null, "Data  berhasil dihapus!");
                        statusAwal();
                      
            }
            catch(SQLException ex){
                Logger.getLogger(FormPegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRubahActionPerformed
        
        
         if(tabelDaftarTunjangan.getSelectedRow() != -1){
            int ind = tabelDaftarTunjangan.convertRowIndexToModel(tabelDaftarTunjangan.getSelectedRow());
            viewTunjangan vT = record.get(ind);
            FormEditTunjangan formEditTunjangan = new FormEditTunjangan(this, true);
            formEditTunjangan.editTunjangan(vT);
            //loadPendidikan();
        }else{
            JOptionPane.showMessageDialog(this, "Anda belum menyeleksi data !!", "Wury's progam", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_cmdRubahActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cmdKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdRubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDaftarTunjangan;
    private javax.swing.JTextField txtIdTunjangan;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
          try{
            record = vTService.getAll();
        }
        catch(SQLException ex){
            Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setWidth() {
        tabelDaftarTunjangan.getColumnModel().getColumn(0).setPreferredWidth(45);
        tabelDaftarTunjangan.getColumnModel().getColumn(1).setPreferredWidth(45);
 
    }
     void isiText() {
         
        viewTunjangan vT = record.get(row);
        String idTunjangan=String.valueOf(vT.getIdTunjangan());
        txtIdTunjangan.setText(idTunjangan);
        
    }
      void isiTextTodetail() {
        FormTunjangan ft=new FormTunjangan();
        viewTunjangan vT = record.get(row);
        String idTunjangan=String.valueOf(vT.getIdTunjangan());
        txtIdTunjangan.setText(idTunjangan);
        
        
    }
   
}
