/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.DaftarGolongan;
import entity.Pegawai;
import implement.DaftarGolonganImplement;
import implement.PegawaiImplement;
import interfce.PegawaiInterface;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import utility.DateUtility;

/**
 *
 * @author aa
 */
public class FormPegawai extends javax.swing.JInternalFrame {
List<Pegawai>record=new ArrayList<>();
DateUtility du = new DateUtility();
    PegawaiInterface pService;
    int row;
    /**
     * Creates new form FormPegawai
     */
    public FormPegawai() {
        initComponents();
        pService=new PegawaiImplement();
             tabelPegawai.getSelectionModel().addListSelectionListener((ListSelectionEvent e)->{
            row = tabelPegawai.getSelectedRow();
            if(row!=-1){
            isiText();
            }
        });
       statusAwal();
        
    }
     void statusAwal(){
        //kosongkanText();
        loadData();
        isiTabel();
    }
     
     public JTextField getTextTanggalLahir() {
        return txtTanggalLahir;
    }

    public void setTextTanggalLahir(JTextField textTanggalLahir) {
        this.txtTanggalLahir = textTanggalLahir;
    }
     public final void setWidth() {
        tabelPegawai.getColumnModel().getColumn(0).setPreferredWidth(45);
        tabelPegawai.getColumnModel().getColumn(1).setPreferredWidth(60);
        tabelPegawai.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelPegawai.getColumnModel().getColumn(3).setPreferredWidth(90);
        tabelPegawai.getColumnModel().getColumn(4).setPreferredWidth(80);
        tabelPegawai.getColumnModel().getColumn(11).setPreferredWidth(100);
        
        
    }
   
     void loadData(){
        try{
            record = pService.getAll();
        }
        catch(SQLException ex){
            Logger.getLogger(FormPegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPegawai = new javax.swing.JTable();
        txtIdPegawai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtNip = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        cbJenisKelamin = new javax.swing.JComboBox();
        cbAgama = new javax.swing.JComboBox();
        txtJabatan = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtTanggalMasuk = new javax.swing.JTextField();
        txtStatusNikah = new javax.swing.JTextField();
        cmdSimpan = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        txtTanggalLahir = new javax.swing.JTextField();
        cbStatusPegawai = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Master Pegawai");

        jLabel2.setText("IDpegawai");

        jLabel3.setText("NIP");

        jLabel4.setText("Nama");

        jLabel5.setText("Tempat Lahir");

        jLabel6.setText("Tanggal Lahir");

        jLabel7.setText("Jenis Kelamin");

        jLabel8.setText("Agama");

        jLabel9.setText("Jabatan");

        jLabel10.setText("Alamat");

        jLabel11.setText("NoTelepon");

        jLabel12.setText("Tanggal Masuk");

        jLabel13.setText("Status Pernikahan");

        jLabel14.setText("Status Pegawai");

        tabelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPegawai);

        txtIdPegawai.setEnabled(false);
        txtIdPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPegawaiActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        txtTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatLahirActionPerformed(evt);
            }
        });

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));

        cbAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Budha", "Hindu", "Katolik" }));

        txtJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJabatanActionPerformed(evt);
            }
        });

        txtTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleponActionPerformed(evt);
            }
        });

        txtTanggalMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalMasukActionPerformed(evt);
            }
        });

        txtStatusNikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusNikahActionPerformed(evt);
            }
        });

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        txtTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalLahirActionPerformed(evt);
            }
        });

        cbStatusPegawai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tetap", "Training", "Kontrak" }));
        cbStatusPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusPegawaiActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("YYYY-MM-DD");

        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(214, 214, 214)
                                                .addComponent(cbStatusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtStatusNikah, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                            .addComponent(txtTanggalMasuk))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)))))
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(272, 272, 272)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(246, 246, 246))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdHapus)
                .addGap(681, 681, 681)
                .addComponent(cmdKeluar)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatusPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(txtTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtStatusNikah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdUbah)
                    .addComponent(cmdHapus)
                    .addComponent(cmdKeluar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPegawaiActionPerformed

    private void txtTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatLahirActionPerformed

    private void txtJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJabatanActionPerformed

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponActionPerformed

    private void txtStatusNikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusNikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusNikahActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void txtTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalLahirActionPerformed
    
    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        // TODO add your handling code here:
        String cekid=txtIdPegawai.getText();
        String cekNip=txtNip.getText();
        String cekNama=txtNama.getText();
        String cekAlamat=txtAlamat.getText();
        String cekTempatLahir=txtTempatLahir.getText();
        
        
   
        
        if(cekNip.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "NIP Harus Di Isi!");
        }else  if(!du.isDateValid(txtTanggalLahir.getText())){
            JOptionPane.showMessageDialog(null, "Tanggal Lahir tidak valid");
        }else  if(!du.isDateValid(txtTanggalMasuk.getText())){
            JOptionPane.showMessageDialog(null, "Tanggal Masuk tidak valid");
        }else{
            try{
        
                
                Pegawai p = new Pegawai();
               
                
                p.setNip(txtNip.getText());
                p.setNamaPegawai(txtNama.getText());
                p.setTempatLahir(txtTempatLahir.getText());
                p.setNamaPegawai(txtNama.getText());
                Date tanggalLahir=du.createDate(txtTanggalLahir.getText());
                p.setTanggalLahir(tanggalLahir);
                p.setJenisKelamin((String) cbJenisKelamin.getSelectedItem());
                p.setAgama((String) cbAgama.getSelectedItem());
                p.setJabatan(txtJabatan.getText());
                p.setAlamat(txtAlamat.getText());
                p.setNoTelpon(txtTelepon.getText());
                 Date tanggalBergabung=du.createDate(txtTanggalMasuk.getText());
                 p.setTanggalBergabung(tanggalBergabung);
                 p.setStatusKawin(txtStatusNikah.getText());
                 p.setStatusPekerjaan((String) cbStatusPegawai.getSelectedItem());
                
                
                
                
                
                pService.insert(p);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data pegawai berhasil disimpan!");
            }
            catch(SQLException ex){
                Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        statusAwal();
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void txtTanggalMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalMasukActionPerformed

    private void cbStatusPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusPegawaiActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
       String cekId = txtIdPegawai.getText();
        
        if(cekId.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih pegawai yang ingin dihapus!");
        }else{
            try{
                Pegawai p = new Pegawai();
                String id = txtIdPegawai.getText();
                pService.delete(id);
          
                        JOptionPane.showMessageDialog(null, "Data  berhasil dihapus!");
                        statusAwal();
                      
            }
            catch(SQLException ex){
                Logger.getLogger(FormPegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
      String cekId = txtIdPegawai.getText();
        
        if(cekId.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih pegawai yang ingin dihapus!");
        }else{
            try{
                Pegawai  p = new Pegawai();
                p.setIdPegawai(txtIdPegawai.getText());
                p.setNip(txtNip.getText());
                p.setNamaPegawai(txtNama.getText());
                p.setTempatLahir(txtTempatLahir.getText());
                p.setNamaPegawai(txtNama.getText());
                Date tanggalLahir=du.createDate(txtTanggalLahir.getText());
                p.setTanggalLahir(tanggalLahir);
                p.setJenisKelamin((String) cbJenisKelamin.getSelectedItem());
                p.setAgama((String) cbAgama.getSelectedItem());
                p.setJabatan(txtJabatan.getText());
                p.setAlamat(txtAlamat.getText());
                p.setNoTelpon(txtTelepon.getText());
                 Date tanggalBergabung=du.createDate(txtTanggalMasuk.getText());
                 p.setTanggalBergabung(tanggalBergabung);
                 p.setStatusKawin(txtStatusNikah.getText());
                 p.setStatusPekerjaan((String) cbStatusPegawai.getSelectedItem());
                
                pService.update(p);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data berhasil dirubah!");
                        statusAwal();
            }
            catch(SQLException ex){
                Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdUbahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAgama;
    private javax.swing.JComboBox cbJenisKelamin;
    private javax.swing.JComboBox cbStatusPegawai;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelPegawai;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtIdPegawai;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtStatusNikah;
    private javax.swing.JTextField txtTanggalLahir;
    private javax.swing.JTextField txtTanggalMasuk;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables

    private void isiText() {

        Pegawai p = record.get(row);
        txtNip.setText(p.getNipPegawai());
        txtNama.setText(p.getNamaPegawai());
        txtIdPegawai.setText(p.getIdPegawai());
        txtJabatan.setText(p.getJabatan());
        txtTempatLahir.setText(p.getTempatLahir());
        cbJenisKelamin.setSelectedItem(p.getJenisKelamin());
        cbAgama.setSelectedItem(p.getAgama());
        txtAlamat.setText(p.getAlamat());
        txtTelepon.setText(p.getNoTelpon());
        txtStatusNikah.setText(p.getStatusKawin());
        txtTanggalLahir.setText(p.getTanggalLahirPegawai());
        txtTanggalMasuk.setText(p.getTanggalBergabungpegawai());
           
    }
    void isiTabel(){
         tabelPegawai.clearSelection();
        Object data[][] = new Object[record.size()][13];
        int x = 0;
        for(Pegawai p:record){
            data[x][0] = p.getIdPegawai();
            data[x][1] = p.getNipPegawai();
            data[x][2] = p.getNamaPegawai();
            data[x][3] = p.getTempatLahir();
            data[x][4] = p.getTanggalLahirPegawai();
            data[x][5] = p.getJenisKelamin();
            data[x][6] = p.getAgama();
            data[x][7] = p.getJabatan();
            data[x][8] = p.getAlamat();
            data[x][9] = p.getNoTelpon();
            data[x][10] = p.getTanggalBergabungpegawai();
            data[x][11] = p.getStatusKawin();
            data[x][12] = p.getStatusPekerjaan();
            x++;
        }
            String judul[] = {"ID Pegawai","NIP","Nama","Tempat Lahir","Tanggal Lahir","Jenis Kelamin","Agama","Jabatan","Alamat","Telepon","Tgl Masuk","Status Nikah","Status Pekerjaan"};
        tabelPegawai.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tabelPegawai);
        setWidth();
    }
}
