/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import entity.DaftarGolongan;
import implement.DaftarGolonganImplement;
import interfce.DaftarGolonganInterface;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa
 */
public class FormGolongan extends javax.swing.JInternalFrame{
List<DaftarGolongan>record=new ArrayList<>();
DaftarGolonganInterface dGService;
int row;
    /**
     * Creates new form FormGolongan
     */
    public FormGolongan() {
      
        initComponents();
            dGService=new DaftarGolonganImplement();
             jTabelMasterGolongan.getSelectionModel().addListSelectionListener((ListSelectionEvent e)->{
            row = jTabelMasterGolongan.getSelectedRow();
            if(row!=-1){
            isiText();
            }
        });
          this.statusAwal();
        
    }
    void statusAwal(){
        kosongkanText();
        loadData();
        isiTabel();
    }
     void loadData(){
        try{
            record = dGService.getAll();
        }
        catch(SQLException ex){
            Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     void isiTabel(){
         jTabelMasterGolongan.clearSelection();
        Object data[][] = new Object[record.size()][4];
        int x = 0;
        for(DaftarGolongan dG:record){
            data[x][0] = dG.getId();
            data[x][1] = dG.getNamaGolongan();
            x++;
        }
            String judul[] = {"Kode Golongan","Nama Golongan"};
        jTabelMasterGolongan.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(jTabelMasterGolongan);
        setWidth();
    }
     
    void isiText(){
        DaftarGolongan dG = record.get(row);
        txtKodeGolongan.setText(dG.getId()+"");
        txtNamaGolongan.setText(dG.getNamaGolongan());
        
    }
    public final void setWidth() {
        jTabelMasterGolongan.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTabelMasterGolongan.getColumnModel().getColumn(1).setPreferredWidth(250);
    }
   
 
    public JTextField  getTextKode() {
        return txtKodeGolongan;
    }

    public JTextField getTextNamaGolongan() {
        return txtNamaGolongan;
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKodeGolongan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaGolongan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelMasterGolongan = new javax.swing.JTable();
        cmdSimpan = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Master Golongan");

        jLabel2.setText("Kode Golongan");

        txtKodeGolongan.setEnabled(false);

        jLabel3.setText("Nama Golongan");

        jTabelMasterGolongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTabelMasterGolongan);

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdDelete.setText("Hapus");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdUbah)
                    .addComponent(cmdDelete)
                    .addComponent(cmdKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here
        dispose();
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        // TODO add your handling code here:
        String cekNamaGolongan=txtNamaGolongan.getText();
        
        if(cekNamaGolongan.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Harus Di Isi!");
        }else{
            try{
        
                
                DaftarGolongan dG = new DaftarGolongan();
                dG.setNamaGolongan(txtNamaGolongan.getText());
                
                dGService.insert(dG);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data barang berhasil disimpan!");
            }
            catch(SQLException ex){
                Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        statusAwal();
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        String cekId = txtKodeGolongan.getText();
        
        if(cekId.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih Golongan yang ingin dihapus!");
        }else{
            try{
                DaftarGolongan dG = new DaftarGolongan();
                String id = txtKodeGolongan.getText();
                dGService.delete(id);
          
                        JOptionPane.showMessageDialog(null, "Data  berhasil dihapus!");
                        statusAwal();
                      
            }
            catch(SQLException ex){
                Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
     String cekId = txtKodeGolongan.getText();
        
        if(cekId.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih golongan yang ingin diubah!");
        }else{
            try{
                DaftarGolongan dG = new DaftarGolongan();
                dG.setId_golongan(txtKodeGolongan.getText());
                dG.setNamaGolongan(txtNamaGolongan.getText());
                
                dGService.update(dG);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data berhasil dirubah!");
                        statusAwal();
            }
            catch(SQLException ex){
                Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGolongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGolongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGolongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGolongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGolongan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelMasterGolongan;
    private javax.swing.JTextField txtKodeGolongan;
    private javax.swing.JTextField txtNamaGolongan;
    // End of variables declaration//GEN-END:variables

    private void kosongkanText() {
        txtKodeGolongan.setText("");
        txtNamaGolongan.setText("");
    }

  
}
