/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Pegawai;
import entity.Tunjangan;
import implement.PegawaiImplement;
import implement.TunjanganImplement;
import interfce.TunjanganInterface;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.binding.Bindings;
import javax.swing.JOptionPane;
import utility.DateUtility;
import utility.koneksi;

/**
 *
 * @author aa
 */
public class FormTunjangan extends javax.swing.JDialog {
DateUtility du=new DateUtility();
    TunjanganInterface tService;
    /**
     * Creates new form FormTunjangan
     */
    public FormTunjangan() {
        //setLocationRelativeTo() ;
        initComponents();
         tService=new TunjanganImplement();
    }
    
    void  simpan(){
        TunjanganInterface tunjanganService;
        String cekIdTunjangan=txtIdTunjangan.getText();
        String cekIdPegawai=txtIdPegawai.getText();
        String cekPeriodeTahun=txtPeriodeTahun.getText();
        String cekNamaTunjangan=txtNamaTunjangan.getText();
        String cekTanggalTunjangan=txtTanggalTunjangan.getText();
        String cekNilaiTunjangan=txtNilaiTunjangan.getText();
        
         if(cekIdPegawai.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pegawai Belum Di Input!");
        }else  if(!du.isDateBulanValid(txtPeriodeTahun.getText())){
            JOptionPane.showMessageDialog(null, "Tahun tidak valid");
        }else  if(!du.isDateValid(txtTanggalTunjangan.getText())){
            JOptionPane.showMessageDialog(null, "Tanggal Tunjangan tidak valid");
        }else{
            try{
                Tunjangan tunjangan = new Tunjangan();
                tunjangan.setIdPegawai(Integer.valueOf(txtIdPegawai.getText()));
                tunjangan.setPeriodeBulan((String) cbBulan.getSelectedItem());
                tunjangan.setPeriodeTahun(txtPeriodeTahun.getText());
                tunjangan.setNamaTunjangan(txtNamaTunjangan.getText());
                tunjangan.setNilaiTunjangan(Integer.valueOf(txtNilaiTunjangan.getText()));
                Date tanggalTunjangan=du.createDate(txtTanggalTunjangan.getText());
                tunjangan.setTanggal(tanggalTunjangan);
               // TunjanganImplement ti=new TunjanganImplement();
                tService.insert(tunjangan);
                        //this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data Tunjangan berhasil disimpan!");
            }
            catch(SQLException ex){
                Logger.getLogger(FormGolongan.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        //statusAwal();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdTunjangan = new javax.swing.JTextField();
        txtIdPegawai = new javax.swing.JTextField();
        cbBulan = new javax.swing.JComboBox();
        txtNamaTunjangan = new javax.swing.JTextField();
        txtNilaiTunjangan = new javax.swing.JTextField();
        txtTanggalTunjangan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNamaPegawai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        txtPeriodeTahun = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Tunjangan");

        jLabel2.setText("Id Tunjangan");

        jLabel3.setText("Id Pegawai");

        jLabel4.setText("Periode Bulan");

        jLabel5.setText("Periode Tahun");

        jLabel6.setText("Nama Tunjangan");

        jLabel7.setText("Nilai Tunjangan");

        jLabel8.setText("Tanggal ");

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANUARI", "FEBRUARY", "MARET", "APRIL", "MEI", "JUNI", "JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DESEMBER", " " }));

        jLabel9.setText("Nama Pegawai");

        jButton1.setText("...");

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNilaiTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggalTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdTunjangan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                            .addComponent(txtIdPegawai, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addComponent(txtPeriodeTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(275, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdKeluar)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPeriodeTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtNamaTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtNilaiTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTanggalTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdKeluar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
       int p=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin Menyimpan data","Simpan Data",JOptionPane.YES_NO_OPTION);
        if(p==0){
         try {
                  String sql="select * from Tunjangan where id_tunjangan=?";
                  PreparedStatement pst = koneksi.getConnection().prepareStatement(sql);
                  pst.setString(1,txtIdTunjangan.getText());
                  ResultSet rs=pst.executeQuery();
                  if (rs.next()){
                        JOptionPane.showMessageDialog(null, "Tunjangan Sudah Terpakai  !!");
                        txtIdTunjangan.setText("");
                  }else {
                      simpan();            
                  }
            } catch (SQLException ex) {
                Logger.getLogger(FormPegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
         
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cmdKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbBulan;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtIdPegawai;
    private javax.swing.JTextField txtIdTunjangan;
    private javax.swing.JTextField txtNamaPegawai;
    private javax.swing.JTextField txtNamaTunjangan;
    private javax.swing.JTextField txtNilaiTunjangan;
    private javax.swing.JTextField txtPeriodeTahun;
    private javax.swing.JTextField txtTanggalTunjangan;
    // End of variables declaration//GEN-END:variables
}
